Server-MOTD: 
  Line-1: "&b&l&m-----------[&r&6&l MangoAal &b&l&m]-----------"
  Line-2: "&4&lMangoAal252660 &eServer1"

JoinGame-MOTD:
  Enabled: true
  Messages:
    - 'Welcome back User'

Max-Players: 20
