Server-MOTD: 
  Line-1: "&b&l&m-----------[&r&6&l Spigot &b&l&m]-----------"
  Line-2: "&e&lWebsite &fwww.spigotmc.org"

JoinGame-MOTD:
  Enabled: true
  Messages:
    - 'default motd'

Max-Players: 200